# Generated by Django 5.0.7 on 2024-07-16 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название велосипеда')),
                ('cost_per_minute', models.FloatField(verbose_name='Стоимость аренды за минуту')),
            ],
        ),
        migrations.CreateModel(
            name='BicycleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateTimeField(auto_now_add=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bicycles.bicycle')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bicycle',
            name='user',
            field=models.ManyToManyField(blank=True, through='bicycles.BicycleUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
