# Generated by Django 5.0.7 on 2024-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название велосипеда'),
        ),
    ]
